[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "https://zenithriskstrategy.com/*"
  to = "https://zenithriskstrategies.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.zenithriskstrategy.com/*"
  to = "https://zenithriskstrategies.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/brochures/mechanics-of-apollo-lf-captive-program.pptx"
  to = "/brochures/mechanics-of-apollo-lf-captive-program.pdf"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
